---
application:
  name: "cybercoder"
  project: "test-project-az"
  organization: "QoveryCommunity"
routers:
- name: "main-cybercoder"
  routes:
  - application_name: "cybercoder"
    paths:
    - "/*"
